- name: "breaking-change"
  color: "#310372"
  description: "Marks an important and likely breaking old interface change."
- name: "bug"
  color: "#b71914"
  description: "Something isn't working"
- name: "CI/CD"
  color: "#2356e0"
  description: "This issue/PR relates to CI/CD pipeline change"
- name: "code style"
  color: "#2356e0"
  description: "This issue/PR relates to code style."
- name: "deprecated"
  color: "#999999"
  description: "Feature or component marked as deprecated and will be removed"
- name: "documentation"
  color: "#2356e0"
  description: "This issue/PR relates to or includes documentation."
- name: "duplicate"
  color: "#eeeeee"
  description: "This issue or pull request already exists"
- name: "enhancement"
  color: "#310372"
  description: "Enhancement update for old feature"
- name: "good first issue"
  color: "#310372"
  description: "Good for newcomers"
- name: "help wanted"
  color: "Extra attention is needed"
  description: "#008672"
- name: "log:added"
  color: "#ff935e"
  description: "Changelog mark label. Marks new added features."
- name: "log:breaking-change"
  color: "#ff935e"
  description: "Changelog mark label. Marks breaking changes."
- name: "log:changed"
  color: "#ff935e"
  description: "Changelog mark label. Marks old, but changed features."
- name: "log:deprecated"
  color: "#ff935e"
  description: "Changelog mark label. Marks deprecated features, that will be removed in next major release."
- name: "log:fixed"
  color: "#ff935e"
  description: "Changelog mark label. Marks fixed bug issues."
- name: "log:removed"
  color: "#ff935e"
  description: "Changelog mark label. Marks removed features."
- name: "log:skip-changelog"
  color: "#ff935e"
  description: "Should be excluded from the changelog."
- name: "os: linux"
  color: "#fbca04"
  description: "This issue/PR related to linux systems"
- name: "os: mac"
  color: "#fbca04"
  description: "This issue/PR related to mac systems"
- name: "os: windows"
  color: "#fbca04"
  description: "This issue/PR related to windows systems"
- name: "question"
  color: "#d876e3"
  description: "User questions, not related to issues"
- name: "tests"
  color: "#2356e0"
  description: "This issue/PR relates to tests, QA, CI."
- name: "waiting-for-contributor"
  color: "#75a6ce"
  description: "Waiting for answer from original contributor."
- name: "WIP"
  color: "#ff3acd"
  description: "Work In Progress"
- name: "wontfix"
  color: "#eeeeee"
  description: "This will not be worked on"
- name: "wontmerge"
  color: "#eeeeee"
  description: "PR Only: This pull request will not be merged (problem described in comments)"
