name: Run checks

on:
  pull_request:
  push:
    branches: [master]

jobs:
  tox:
    strategy:
      fail-fast: false
      matrix:
        platform: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python: ["3.7", "3.8"]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
    - name: Install nox
      run: |
        python -m pip install --upgrade pip
        python -m pip install nox
    - name: Run nox
      run: nox -s tests-${{ matrix.python }}
