name: Run checks

on: [push, pull_request]

jobs:
  tox:
    strategy:
      fail-fast: false
      matrix:
        platform: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python: ["3.7", "3.8"]
        noxsession: ["tests"]

        include:
          - noxsession: "linting"
            python: "3.8"
            platform: "ubuntu-latest"
          - noxsession: "coverage"
            python: "3.8"
            platform: "ubuntu-latest"

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
    - name: Install nox
      run: |
        python -m pip install --upgrade pip
        python -m pip install nox
    - name: Run tox
      run: |
        nox -s ${{ matrix.noxsession }}
