name: Run checks

on:
  pull_request:
  push:
    branches: [master]

jobs:
  nox:
    strategy:
      fail-fast: false
      matrix:
        platform: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python: ["3.7", "3.8"]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
    - name: Install nox
      run: |
        python -m pip install --upgrade pip
        python -m pip install nox
    - name: Run pytest tests with nox
      run: nox -s tests-${{ matrix.python }}
    - name: Send coverage report to codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
    - name: Send coverage report to codeclimate
      uses: paambaati/codeclimate-action@v2.6.0
      with:
        coverageCommand: echo "Ignore rerun"
        coverageLocations: ${{github.workspace}}/.coverage
      env:
        CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
