name: "Documentation build check"
on:
  pull_request:
    branches:
      - "*"

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - uses: actions/setup-python@v1
        with:
          python-version: "3.7"
      - uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "docs/"
      - uses: actions/upload-artifact@v1
        with:
          name: DocumentationHTML
          path: docs/build/html/
