name: Labels verification

on:
  push:
    branches: [master]

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Labeler
        uses: crazy-max/ghaction-github-labeler@v2
        with:
          yaml_file: .github/labels.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
